// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxfeAUA9uaiISGFxmKja_GO1fLsUlnQdU',
    appId: '1:1004725949164:web:e09056f94bf8d08d8b0bc9',
    messagingSenderId: '1004725949164',
    projectId: 'fptapp',
    authDomain: 'fptapp.firebaseapp.com',
    storageBucket: 'fptapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrDdq1yE41P-Ahnx78Sol8dE2k-MPKXW0',
    appId: '1:1004725949164:android:09175f76afc95e5c8b0bc9',
    messagingSenderId: '1004725949164',
    projectId: 'fptapp',
    storageBucket: 'fptapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ofkyF1LksvMaLz4mHr8Ov4gHJrB75F8',
    appId: '1:1004725949164:ios:083754972b7a8e8f8b0bc9',
    messagingSenderId: '1004725949164',
    projectId: 'fptapp',
    storageBucket: 'fptapp.firebasestorage.app',
    iosBundleId: 'edu.FPT.fptapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ofkyF1LksvMaLz4mHr8Ov4gHJrB75F8',
    appId: '1:1004725949164:ios:083754972b7a8e8f8b0bc9',
    messagingSenderId: '1004725949164',
    projectId: 'fptapp',
    storageBucket: 'fptapp.firebasestorage.app',
    iosBundleId: 'edu.FPT.fptapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxfeAUA9uaiISGFxmKja_GO1fLsUlnQdU',
    appId: '1:1004725949164:web:b0a0f99a221111628b0bc9',
    messagingSenderId: '1004725949164',
    projectId: 'fptapp',
    authDomain: 'fptapp.firebaseapp.com',
    storageBucket: 'fptapp.firebasestorage.app',
  );

}